# Generated by Django 4.2.1 on 2023-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
