# Generated by Django 4.2.1 on 2023-05-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_alter_scrapeddoctors_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddoctors',
            name='experience',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='scrapeddoctors',
            name='image_url',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='scrapeddoctors',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scrapeddoctors',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scrapeddoctors',
            name='specialty',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapeddoctors',
            name='url',
            field=models.CharField(max_length=10000),
        ),
    ]
