# Generated by Django 4.2.1 on 2023-06-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_rename_specialty_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(default='Country not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewscraped',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapeddoctors',
            name='country',
            field=models.CharField(default='Country not provided', max_length=100),
        ),
        migrations.CreateModel(
            name='DoctorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField(default=0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.scrapeddoctors')),
            ],
        ),
    ]
