# Generated by Django 4.2.1 on 2023-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0007_doctor_country_reviewscraped_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddoctors',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
