# Generated by Django 4.2.1 on 2023-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_alter_patient_image'),
        ('doctor_app', '0009_doctor_address_doctor_birth_date_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddoctors',
            name='insurance',
            field=models.ManyToManyField(blank=True, null=True, to='patient_app.insurance'),
        ),
    ]
